# OML properties
oml:
   version: 2.13.0

# Project properties
project:
   title: Dave Demo 3
   description: Interface management model kinda like CAESAR
   group: io.github.dw-oml-3
   version: 0.1.0

# Maven repositories
repositories:
   - https://repo.maven.apache.org/maven2

# Maven dependencies
dependencies:
   - io.opencaesar.ontologies:core-vocabularies:5.+